import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import catalogJson from '@/data/agency-catalog.json'

/* ------------------------------------------------------------------ */
/* The Agency — 255 specialist AI personas from                        */
/* github.com/msitarzewski/agency-agents (MIT).                        */
/* Metadata ships as a compact JSON catalog (src/data/agency-catalog   */
/* .json, generated by scripts/build-agency-catalog.mjs); full persona */
/* prompts live on disk under data/agency/<division>/<slug>.md and     */
/* are read + cached here at runtime.                                  */
/* ------------------------------------------------------------------ */

export interface AgencyDivision {
  id: string
  label: string
  /** Lucide icon name (PascalCase) — rendered by DIVISION_ICONS below. */
  icon: string
  /** Brand color (hex) from the upstream divisions.json. */
  color: string
  count: number
}

export interface AgencyAgent {
  slug: string
  name: string
  division: string
  description: string
  emoji: string
  vibe: string
}

export interface AgencyCatalog {
  stats: { agents: number; divisions: number }
  divisions: AgencyDivision[]
  agents: AgencyAgent[]
}

export const AGENCY_CATALOG = catalogJson as unknown as AgencyCatalog

export const AGENCY_STATS = AGENCY_CATALOG.stats
export const AGENCY_DIVISIONS = AGENCY_CATALOG.divisions
export const AGENCY_AGENTS = AGENCY_CATALOG.agents

const DIVISION_MAP = new Map(AGENCY_DIVISIONS.map((d) => [d.id, d]))
const AGENT_MAP = new Map(AGENCY_AGENTS.map((a) => [a.slug, a]))

export function getDivision(id: string): AgencyDivision | undefined {
  return DIVISION_MAP.get(id)
}

export function getAgentMeta(slug: string): AgencyAgent | undefined {
  return AGENT_MAP.get(slug)
}

/* ------------------------------------------------------------------ */
/* Persona prompt loading (server-only, cached in module memory)       */
/* ------------------------------------------------------------------ */

const promptCache = new Map<string, string>()

/**
 * Loads the full persona prompt for an agent slug. The file's markdown
 * body (everything after the frontmatter) IS the system prompt — the
 * upstream files are written as agent personality definitions.
 * Returns null for unknown slugs (caller falls back to the default
 * NEXUS persona).
 */
export function getAgentPrompt(slug: string): string | null {
  if (promptCache.has(slug)) return promptCache.get(slug)!

  const meta = AGENT_MAP.get(slug)
  if (!meta) return null

  try {
    const filePath = join(process.cwd(), 'data', 'agency', meta.division, `${slug}.md`)
    const raw = readFileSync(filePath, 'utf8')
    // Strip frontmatter — keep the markdown body (the persona itself).
    const body = raw.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/, '').trim()
    promptCache.set(slug, body)
    return body
  } catch (error) {
    console.error(`[agency] failed to load prompt for ${slug}:`, error)
    return null
  }
}

/**
 * Wraps a persona prompt with the framing the chat pipeline expects:
 * the agent stays itself, but knows it is chatting inside NEXUS with
 * the full NEXUS toolbox (images, documents, code, web search…).
 */
export function buildPersonaSystemPrompt(slug: string): string | null {
  const meta = AGENT_MAP.get(slug)
  const prompt = getAgentPrompt(slug)
  if (!meta || !prompt) return null

  const division = DIVISION_MAP.get(meta.division)
  return [
    `You are "${meta.name}"${division ? ` of the ${division.label} division` : ''} — a specialist agent in The Agency, NEXUS's team of ${AGENCY_STATS.agents} AI experts.`,
    ``,
    prompt,
    ``,
    `OPERATING NOTES:`,
    `- Stay fully in character as ${meta.name}. Your personality, processes and deliverables above shape every answer.`,
    `- You are chatting inside NEXUS, so you also have the NEXUS toolbox available (image generation, document creation, code execution, web search…). Use them when they serve the user.`,
    `- Keep answers practical and deliverable-focused, as defined in your persona.`,
  ].join('\n')
}

/** Safe listing for API responses (metadata only — never prompts). */
export function listAgents(): AgencyAgent[] {
  return AGENCY_AGENTS
}

export function listDivisions(): AgencyDivision[] {
  return AGENCY_DIVISIONS
}
