import { randomBytes } from 'crypto'
import { db } from '@/lib/db'
import { encryptSecret, decryptSecret } from '@/lib/email'
import { smartChat } from '@/lib/smart-chat'

/* ------------------------------------------------------------------ */
/* WhatsApp Business Cloud API — NEXUS integration library             */
/*                                                                     */
/* Phase 1 (test number flow):                                         */
/*   • Meta gives every developer app a FREE test number that can      */
/*     message up to 5 verified recipients — no business docs needed.  */
/*   • Sending works immediately with a temporary access token.        */
/*   • Receiving (webhook) works on the deployed URL (Vercel).         */
/*                                                                     */
/* All Graph API calls go to graph.facebook.com with the account's     */
/* bearer token. Replies to customers are generated by the same        */
/* smart-chat pool that powers the NEXUS chat UI.                      */
/* ------------------------------------------------------------------ */

const GRAPH_VERSION = 'v21.0'
const GRAPH_BASE = `https://graph.facebook.com/${GRAPH_VERSION}`

/** Max characters for a WhatsApp text message (API hard limit is 4096). */
const WA_TEXT_LIMIT = 3500

/* ------------------------------------------------------------------ */
/* Types                                                               */
/* ------------------------------------------------------------------ */

export interface WhatsAppAccountRecord {
  id: string
  label: string
  businessName: string
  phoneNumberId: string
  displayPhone: string
  verifyToken: string
  status: string
  statusMessage: string
  autoReply: boolean
  agentPrompt: string
  allowList: string
  webhookVerified: boolean
  createdAt: Date
  updatedAt: Date
}

export interface PublicWhatsAppAccount {
  id: string
  label: string
  businessName: string
  phoneNumberId: string
  displayPhone: string
  verifyToken: string
  status: string
  statusMessage: string
  autoReply: boolean
  agentPrompt: string
  allowList: string[]
  webhookVerified: boolean
  hasToken: boolean
  tokenPreview: string
  createdAt: string
  updatedAt: string
}

/* ------------------------------------------------------------------ */
/* Helpers                                                             */
/* ------------------------------------------------------------------ */

/**
 * SECURITY: WhatsApp connections are now PRIVATE per user. Pass the
 * verified session's userId to fetch the caller's own account.
 * - `getWhatsAppAccount(userId)` → the caller's account (UI + send tools).
 * - `getWhatsAppAccount()` (no arg) → returns null. The old "any account"
 *   behaviour was the data-exposure bug; it is intentionally gone.
 * - The Meta webhook resolves its account by verifyToken (see
 *   getWhatsAppAccountByVerifyToken below), independent of userId.
 */
export async function getWhatsAppAccount(userId?: string | null): Promise<WhatsAppAccountRecord | null> {
  try {
    if (!userId) return null
    const account = await db.whatsAppAccount.findFirst({
      where: { userId },
      orderBy: { createdAt: 'asc' },
    })
    return account as unknown as WhatsAppAccountRecord | null
  } catch (error) {
    console.error('[whatsapp] getWhatsAppAccount error:', error)
    return null
  }
}

/** Used by the Meta webhook — resolves the account to verify against. */
export async function getWhatsAppAccountByVerifyToken(
  verifyToken: string
): Promise<WhatsAppAccountRecord | null> {
  try {
    if (!verifyToken) return null
    const account = await db.whatsAppAccount.findFirst({
      where: { verifyToken },
    })
    return account as unknown as WhatsAppAccountRecord | null
  } catch (error) {
    console.error('[whatsapp] getWhatsAppAccountByVerifyToken error:', error)
    return null
  }
}

/** Used by the Meta webhook POST — resolves the account that owns a given
 *  Meta phone_number_id, so inbound messages route to the right user. */
export async function getWhatsAppAccountByPhoneNumberId(
  phoneNumberId: string
): Promise<WhatsAppAccountRecord | null> {
  try {
    if (!phoneNumberId) return null
    const account = await db.whatsAppAccount.findFirst({
      where: { phoneNumberId },
    })
    return account as unknown as WhatsAppAccountRecord | null
  } catch (error) {
    console.error('[whatsapp] getWhatsAppAccountByPhoneNumberId error:', error)
    return null
  }
}

/** Strip everything but digits (E.164 without the leading +). */
export function normalizeWaNumber(raw: string): string {
  return (raw || '').replace(/[^\d]/g, '')
}

/** Public, token-safe representation for the UI. */
export function toPublicAccount(account: WhatsAppAccountRecord): PublicWhatsAppAccount {
  let tokenPreview = ''
  try {
    const plain = decryptSecret(
      (account as unknown as { accessTokenEnc: string }).accessTokenEnc
    )
    tokenPreview = plain.length > 12 ? `${plain.slice(0, 6)}…${plain.slice(-4)}` : '••••'
  } catch {
    tokenPreview = '••••'
  }
  let allowList: string[] = []
  try {
    const parsed = JSON.parse(account.allowList || '[]')
    if (Array.isArray(parsed)) allowList = parsed.filter((n) => typeof n === 'string')
  } catch {
    /* ignore malformed JSON */
  }
  return {
    id: account.id,
    label: account.label,
    businessName: account.businessName,
    phoneNumberId: account.phoneNumberId,
    displayPhone: account.displayPhone,
    verifyToken: account.verifyToken,
    status: account.status,
    statusMessage: account.statusMessage,
    autoReply: account.autoReply,
    agentPrompt: account.agentPrompt,
    allowList,
    webhookVerified: account.webhookVerified,
    hasToken: true,
    tokenPreview,
    createdAt: account.createdAt.toISOString(),
    updatedAt: account.updatedAt.toISOString(),
  }
}

/** Generate a webhook verify token (32 hex chars). */
export function generateVerifyToken(): string {
  return randomBytes(16).toString('hex')
}

/* ------------------------------------------------------------------ */
/* Cloud API client                                                    */
/* ------------------------------------------------------------------ */

export interface WaSendResult {
  ok: boolean
  waMessageId?: string
  error?: string
}

/** Send a plain-text WhatsApp message via the Cloud API. */
export async function waSendText(
  account: WhatsAppAccountRecord,
  to: string,
  body: string
): Promise<WaSendResult> {
  const recipient = normalizeWaNumber(to)
  if (!recipient) return { ok: false, error: 'Missing recipient number.' }

  let token: string
  try {
    token = decryptSecret((account as unknown as { accessTokenEnc: string }).accessTokenEnc)
  } catch {
    return { ok: false, error: 'Stored access token is corrupted — reconnect the account.' }
  }

  const text = body.length > WA_TEXT_LIMIT ? `${body.slice(0, WA_TEXT_LIMIT - 1)}…` : body

  try {
    const res = await fetch(`${GRAPH_BASE}/${account.phoneNumberId}/messages`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        messaging_product: 'whatsapp',
        recipient_type: 'individual',
        to: recipient,
        type: 'text',
        text: { preview_url: false, body: text },
      }),
      signal: AbortSignal.timeout(20_000),
    })

    const data = (await res.json().catch(() => ({}))) as {
      messages?: { id: string }[]
      error?: { message?: string; code?: number }
    }

    if (!res.ok) {
      const message = data.error?.message || `Cloud API error (HTTP ${res.status})`
      console.error('[whatsapp] send failed:', message)
      return { ok: false, error: message }
    }

    return { ok: true, waMessageId: data.messages?.[0]?.id }
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Network error contacting Meta'
    console.error('[whatsapp] send error:', message)
    return { ok: false, error: message }
  }
}

/** Mark a customer message as read (blue ticks) — best effort. */
export async function waMarkRead(
  account: WhatsAppAccountRecord,
  messageId: string
): Promise<void> {
  try {
    const token = decryptSecret((account as unknown as { accessTokenEnc: string }).accessTokenEnc)
    await fetch(`${GRAPH_BASE}/${account.phoneNumberId}/messages`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        messaging_product: 'whatsapp',
        status: 'read',
        message_id: messageId,
      }),
      signal: AbortSignal.timeout(10_000),
    })
  } catch {
    /* best-effort — ignore failures */
  }
}

/* ------------------------------------------------------------------ */
/* The NEXUS auto-reply brain                                          */
/* ------------------------------------------------------------------ */

/** Default persona when the user hasn't written a custom one. */
export const DEFAULT_AGENT_PROMPT = `You are the WhatsApp assistant for a small business in Dubai. You reply to customer messages quickly, warmly and professionally.

Rules:
- Keep replies SHORT (under 120 words) — this is WhatsApp, not email.
- Use a friendly, human tone. Light emoji use is fine (max 1-2).
- If you don't know something (prices, availability, addresses), say you'll check and ask for a moment rather than inventing facts.
- Never invent order numbers, payment links or personal data.
- Reply in the same language the customer writes in (English or Arabic).`

/** How many past messages (per customer) the agent remembers. */
const MEMORY_DEPTH = 12

/**
 * Generate an agent reply for an incoming customer message.
 * Builds conversation history from the stored message log, routes
 * through the NEXUS smart-chat pool, and returns WhatsApp-ready text.
 */
export async function generateAgentReply(
  account: WhatsAppAccountRecord,
  fromNumber: string,
  incomingText: string,
  contactName?: string
): Promise<string> {
  // Recent conversation with this customer (oldest → newest)
  const history = await db.whatsAppMessage.findMany({
    where: { fromNumber, direction: { in: ['in', 'out'] } },
    orderBy: { createdAt: 'desc' },
    take: MEMORY_DEPTH,
  })
  history.reverse()

  const persona = account.agentPrompt?.trim() || DEFAULT_AGENT_PROMPT

  const systemPrompt = `${persona}

You are replying inside WhatsApp on behalf of "${account.businessName}".
${contactName ? `The customer's name is ${contactName}.` : ''}
Current date/time context: ${new Date().toISOString()}
Stay concise and WhatsApp-native. Plain text only — no markdown headers, no bullet symbols beyond simple dashes.`

  const messages: Array<{ role: string; content: string }> = [{ role: 'system', content: systemPrompt }]

  for (const msg of history) {
    // Skip the just-saved incoming message — it's appended below as the final user turn
    if (msg.direction === 'in' && msg.body === incomingText && msg.createdAt.getTime() > Date.now() - 15_000) {
      // include it only once (it IS the latest message; history may already contain it)
      const isLast = history[history.length - 1]?.id === msg.id
      if (isLast) continue
    }
    messages.push({
      role: msg.direction === 'in' ? 'user' : 'assistant',
      content: msg.body,
    })
  }

  messages.push({ role: 'user', content: incomingText })

  try {
    const reply = await smartChat(messages, {
      task: 'chat',
      maxTokens: 500,
      temperature: 0.7,
      timeoutMs: 45_000,
    })

    const trimmed = reply.trim()
    if (!trimmed) {
      return "Hi! Thanks for your message — we'll get back to you shortly. 🙏"
    }
    return trimmed
  } catch (error) {
    console.error('[whatsapp] agent reply failed:', error)
    return "Thanks for your message! We received it and will reply personally in a moment. 🙏"
  }
}

/* ------------------------------------------------------------------ */
/* Message persistence                                                 */
/* ------------------------------------------------------------------ */

export async function saveInboundMessage(
  accountId: string,
  fromNumber: string,
  toNumber: string,
  body: string,
  waMessageId: string
): Promise<boolean> {
  // Dedupe: Meta retries webhooks aggressively
  const existing = await db.whatsAppMessage.findFirst({
    where: { waMessageId, direction: 'in' },
  })
  if (existing) return false

  await db.whatsAppMessage.create({
    data: {
      accountId,
      fromNumber,
      toNumber,
      direction: 'in',
      body,
      waMessageId,
      status: 'received',
    },
  })
  return true
}

export async function saveOutboundMessage(
  accountId: string,
  fromNumber: string,
  toNumber: string,
  body: string,
  waMessageId: string | null,
  status: string
): Promise<void> {
  await db.whatsAppMessage.create({
    data: {
      accountId,
      fromNumber,
      toNumber,
      direction: 'out',
      body,
      waMessageId: waMessageId ?? undefined,
      status,
    },
  })
}
