-- ============================================================================
-- NEXUS AI — Supabase Postgres Schema (auto-generated from prisma/schema.prisma)
-- ============================================================================
-- Run this in: Supabase Dashboard → SQL Editor → New Query → paste → Run.
--
-- This creates ALL 13 tables the app needs, with the EXACT names + columns
-- Prisma expects (PascalCase, TEXT cuid() IDs, no references to auth.users).
-- NON-DESTRUCTIVE & IDEMPOTENT: no DROP statements — CREATE TABLE IF NOT
-- EXISTS everywhere, so re-running provisions missing tables and NEVER wipes
-- existing rows (a destructive re-run once orphaned 30-day session cookies and
-- caused `Foreign key constraint violated on ChatSession_userId_fkey`).
--
-- Tables: User, ChatSession, ChatMessage, GeneratedImage, GeneratedVideo,
--         GeneratedDocument, EmailAccount, AiProvider, UserMemory, Project,
--         ProjectFile, WhatsAppAccount, WhatsAppMessage
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. CLEANUP — drop old wrong tables (snake_case + UUID + auth.users refs)
--    AND drop any prior version of the correct tables. CASCADE handles deps.
-- ---------------------------------------------------------------------------
-- Old wrong tables (from a previous, incompatible version of this file)

-- ---------------------------------------------------------------------------
-- 2. CREATE TABLES (generated by `prisma migrate diff --from-empty`)
-- ---------------------------------------------------------------------------

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE IF NOT EXISTS "ChatSession" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL DEFAULT 'New conversation',
    "kind" TEXT NOT NULL DEFAULT 'chat',
    "agentSlug" TEXT,
    "agentPinned" BOOLEAN NOT NULL DEFAULT false,
    "userId" TEXT,
    "projectId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ChatSession_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "ChatMessage" (
    "id" TEXT NOT NULL,
    "sessionId" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "thinking" TEXT,
    "toolName" TEXT,
    "toolData" TEXT,
    "attachments" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ChatMessage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "GeneratedImage" (
    "id" TEXT NOT NULL,
    "prompt" TEXT NOT NULL,
    "size" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "provider" TEXT NOT NULL DEFAULT 'nexus',
    "data" TEXT,
    "userId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "GeneratedImage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "GeneratedVideo" (
    "id" TEXT NOT NULL,
    "prompt" TEXT NOT NULL,
    "scenes" INTEGER NOT NULL DEFAULT 4,
    "voice" TEXT NOT NULL DEFAULT 'en-US-AriaNeural',
    "style" TEXT NOT NULL DEFAULT 'cinematic',
    "url" TEXT,
    "jobId" TEXT,
    "status" TEXT NOT NULL DEFAULT 'planning',
    "data" TEXT,
    "userId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "GeneratedVideo_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "GeneratedVideo_jobId_key" ON "GeneratedVideo"("jobId");

-- CreateTable
CREATE TABLE IF NOT EXISTS "GeneratedDocument" (
    "id" TEXT NOT NULL,
    "filename" TEXT NOT NULL,
    "format" TEXT NOT NULL DEFAULT 'docx',
    "title" TEXT NOT NULL,
    "summary" TEXT NOT NULL DEFAULT '',
    "downloadUrl" TEXT NOT NULL,
    "size" INTEGER NOT NULL DEFAULT 0,
    "userId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "GeneratedDocument_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "User" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL DEFAULT '',
    "passwordHash" TEXT NOT NULL,
    "interests" TEXT NOT NULL DEFAULT '[]',
    "commStyle" TEXT NOT NULL DEFAULT 'balanced',
    "avatarUrl" TEXT,
    "bio" TEXT,
    "location" TEXT,
    "timezone" TEXT,
    "language" TEXT NOT NULL DEFAULT 'en',
    "jobTitle" TEXT,
    "website" TEXT,
    "notifications" BOOLEAN NOT NULL DEFAULT true,
    "emailVerified" BOOLEAN NOT NULL DEFAULT false,
    "lastActiveAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "EmailAccount" (
    "id" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "fromName" TEXT NOT NULL DEFAULT '',
    "imapHost" TEXT NOT NULL,
    "imapPort" INTEGER NOT NULL DEFAULT 993,
    "smtpHost" TEXT NOT NULL,
    "smtpPort" INTEGER NOT NULL DEFAULT 465,
    "smtpSecure" BOOLEAN NOT NULL DEFAULT true,
    "username" TEXT NOT NULL,
    "passwordEnc" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'unverified',
    "statusMessage" TEXT NOT NULL DEFAULT '',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EmailAccount_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "AiProvider" (
    "id" TEXT NOT NULL,
    "providerId" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "apiKeyEnc" TEXT NOT NULL,
    "baseUrl" TEXT NOT NULL,
    "defaultModel" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'unverified',
    "statusMessage" TEXT NOT NULL DEFAULT '',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AiProvider_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "UserMemory" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "sourceSessionId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "UserMemory_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "Project" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "color" TEXT NOT NULL DEFAULT 'amber',
    "customInstructions" TEXT NOT NULL DEFAULT '',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Project_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "ProjectFile" (
    "id" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "filename" TEXT NOT NULL,
    "mimeType" TEXT NOT NULL DEFAULT 'text/plain',
    "size" INTEGER NOT NULL DEFAULT 0,
    "content" TEXT NOT NULL DEFAULT '',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ProjectFile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "WhatsAppAccount" (
    "id" TEXT NOT NULL,
    "label" TEXT NOT NULL DEFAULT 'WhatsApp Business',
    "businessName" TEXT NOT NULL DEFAULT 'NEXUS Assistant',
    "phoneNumberId" TEXT NOT NULL,
    "displayPhone" TEXT NOT NULL DEFAULT '',
    "accessTokenEnc" TEXT NOT NULL,
    "verifyToken" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "statusMessage" TEXT NOT NULL DEFAULT '',
    "autoReply" BOOLEAN NOT NULL DEFAULT true,
    "agentPrompt" TEXT NOT NULL DEFAULT '',
    "allowList" TEXT NOT NULL DEFAULT '[]',
    "webhookVerified" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "WhatsAppAccount_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "WhatsAppMessage" (
    "id" TEXT NOT NULL,
    "accountId" TEXT NOT NULL,
    "fromNumber" TEXT NOT NULL,
    "toNumber" TEXT NOT NULL,
    "direction" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "waMessageId" TEXT,
    "status" TEXT NOT NULL DEFAULT 'sent',
    "error" TEXT NOT NULL DEFAULT '',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "WhatsAppMessage_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "ChatMessage_sessionId_createdAt_idx" ON "ChatMessage"("sessionId", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "AiProvider_providerId_key" ON "AiProvider"("providerId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "UserMemory_userId_createdAt_idx" ON "UserMemory"("userId", "createdAt");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "Project_userId_updatedAt_idx" ON "Project"("userId", "updatedAt");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "ProjectFile_projectId_createdAt_idx" ON "ProjectFile"("projectId", "createdAt");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "WhatsAppAccount_createdAt_idx" ON "WhatsAppAccount"("createdAt");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "WhatsAppMessage_accountId_createdAt_idx" ON "WhatsAppMessage"("accountId", "createdAt");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "WhatsAppMessage_fromNumber_createdAt_idx" ON "WhatsAppMessage"("fromNumber", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "WhatsAppMessage_waMessageId_direction_key" ON "WhatsAppMessage"("waMessageId", "direction");

-- AddForeignKey
ALTER TABLE "ChatSession" ADD CONSTRAINT "ChatSession_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ChatSession" ADD CONSTRAINT "ChatSession_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ChatMessage" ADD CONSTRAINT "ChatMessage_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "ChatSession"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GeneratedImage" ADD CONSTRAINT "GeneratedImage_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GeneratedVideo" ADD CONSTRAINT "GeneratedVideo_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GeneratedDocument" ADD CONSTRAINT "GeneratedDocument_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserMemory" ADD CONSTRAINT "UserMemory_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Project" ADD CONSTRAINT "Project_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ProjectFile" ADD CONSTRAINT "ProjectFile_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WhatsAppMessage" ADD CONSTRAINT "WhatsAppMessage_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "WhatsAppAccount"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ------------------------------------------------------------------
-- Idempotent upgrades for EXISTING deployments (safe to re-run)
-- ------------------------------------------------------------------

-- Generated bytes persistence (survives Vercel's ephemeral /tmp)
ALTER TABLE "GeneratedImage" ADD COLUMN IF NOT EXISTS "data" TEXT;
ALTER TABLE "GeneratedVideo" ADD COLUMN IF NOT EXISTS "data" TEXT;
ALTER TABLE "GeneratedVideo" ADD COLUMN IF NOT EXISTS "error" TEXT;

-- jobId uniqueness (upsert target for Vercel-safe job state). Deduplicate
-- first so the unique index never fails on legacy rows.
DELETE FROM "GeneratedVideo" a USING "GeneratedVideo" b
WHERE a."jobId" IS NOT NULL AND a."jobId" = b."jobId" AND a."createdAt" < b."createdAt";
CREATE UNIQUE INDEX IF NOT EXISTS "GeneratedVideo_jobId_key" ON "GeneratedVideo"("jobId");

